# Multi-Domain Logical Reasoning Configuration
# Covers: Syllogisms, Seating Arrangements, Family Tree Logic, Mixed Series

# Global paths configuration
paths:
  input: "data/input"           # Source PDFs and text files
  output:
    parsed: "data/parsed"       # Extracted text files (.txt)
    generated: "data/generated" # Generated QA pairs and CoT (.json)
    curated: "data/curated"     # Quality-filtered data (.json)
    final: "data/final"         # Training-ready format (.json)

# LLM Provider configuration
llm:
  provider: "vllm"

# vLLM server configuration
vllm:
  api_base: "http://localhost:8001/v1"
  port: 8001
  model: "unsloth/gpt-oss-120b-GGUF"
  max_retries: 3
  retry_delay: 1.0
  sleep_time: 0.1

# Document processing configuration
ingest:
  default_format: "txt"
  youtube_captions: "auto"

# LLM generation parameters
generation:
  temperature: 0.3       # Lower for more reliable JSON formatting
  top_p: 0.9
  
  # Document processing strategy
  processing_strategy: "auto"
  single_call_max_size: 8000
  
  # Chunking parameters
  chunk_size: 4000
  overlap: 300
  
  # Content generation targets
  num_pairs: 15
  num_cot_examples: 10
  
  # Model parameters
  max_tokens: 4096
  batch_size: 16
  
  # Quality settings
  enable_deduplication: true
  similarity_threshold: 0.85

# Content curation parameters
curate:
  threshold: 7.5
  batch_size: 5
  inference_batch: 5
  temperature: 0.1

# Format conversion parameters
format:
  default: "alpaca"
  include_metadata: true
  pretty_json: true

# Specialized prompts for all 4 domains
prompts:
  # Summary generation
  summary: |
    Summarize this logical reasoning content in 3-5 sentences, focusing on:
    1. The type of logical problems covered (Syllogisms/Seating/Family Tree/Series)
    2. Key solving strategies mentioned
    3. Important concepts and principles
    
  # QA pair generation for all domains
  qa_generation: |
    Create {num_pairs} high-quality question-answer pairs from this educational content.
    
    Analyze the content and generate questions appropriate to these domains:
    
    **SYLLOGISMS:**
    - Focus on: Valid logical inference, testing conclusions against premises, categorical logic
    - Question format: "Statement I: All A are B, Statement II: Some B are C, Statement III: No C is D. Conclusions I: ..., Conclusion II: ..."
    - Answer format: Step-by-step logical deduction showing which conclusions follow
    - Difficulty: Test complex multi-statement reasoning, identify contradictions
    
    **SEATING ARRANGEMENTS (Linear, Circular):**
    - Focus on: Constraint satisfaction, spatial reasoning, systematic placement testing
    - Question format: "In a circular/linear arrangement, A sits 2 seats left of B, C is opposite D, E is not adjacent to F..."
    - Answer format: Show systematic deduction, test different arrangements, eliminate contradictions
    - Difficulty: Multiple interrelated constraints requiring careful tracking
    
    **FAMILY TREE LOGIC:**
    - Focus on: Relationship mapping, generational deduction, indirect relation resolution
    - Question format: "X says 'He is the son of my mother's only brother.' How is X related to the person described?"
    - Answer format: Break down relationships step-by-step, draw family tree mentally, trace connections
    - Difficulty: Use complex indirect references (mother's sister's daughter's son, etc.)
    
    **MIXED SERIES (Alphanumeric):**
    - Focus on: Pattern recognition in combined sequences, multiple simultaneous patterns
    - Question format: "A1B2C3, D4E5F6, G7H8I9, ___"
    - Answer format: Identify separate patterns (letters increase by 3, numbers increase by 1, grouped in 3s), apply to find next term
    - Difficulty: Non-obvious patterns, multiple rules operating simultaneously
    
    **IMPORTANT INSTRUCTIONS:**
    - Generate questions across ALL relevant domains found in the text
    - Make questions EXTREMELY DIFFICULT - test deep understanding, not trivial recall
    - Answers must show COMPLETE step-by-step reasoning
    - Include verification that the answer satisfies all constraints
    - Vary difficulty: basic → intermediate → advanced
    
    **CRITICAL OUTPUT REQUIREMENTS:**
    1. Output ONLY a valid JSON array - nothing else
    2. Start with [ and end with ]
    3. NO markdown code blocks (no ```json, no ```)
    4. NO explanatory text before or after the JSON
    5. Each question must be a complete JSON object
    
    **EXACT FORMAT TO FOLLOW:**
    [
      {{
        "question": "Clear, specific question requiring systematic analysis?",
        "answer": "Complete step-by-step solution showing all reasoning steps, testing assumptions, and reaching the final answer with verification.",
        "difficulty": "basic",
        "domain": "syllogisms"
      }},
      {{
        "question": "Another question from a different domain?",
        "answer": "Detailed answer with step-by-step deduction...",
        "difficulty": "intermediate",
        "domain": "family_tree"
      }}
    ]
    
    Remember: Output ONLY the JSON array. No markdown. No explanations. Just the JSON.
    
    Text:
    {text}
  
  # Chain of Thought generation
  cot_generation: |
    Create {num_pairs} complex multi-domain reasoning problems with detailed chain-of-thought solutions.
    
    For each domain, demonstrate systematic problem-solving:
    
    **SYLLOGISMS CoT Structure:**
    Step 1: List all given statements
    Step 2: Identify what conclusions need to be tested
    Step 3: For each conclusion, check if it follows from the statements
    Step 4: Test for contradictions with given statements
    Step 5: Verify final answer against all statements
    
    **SEATING ARRANGEMENTS CoT Structure:**
    Step 1: List all constraints from the problem
    Step 2: Start with the most restrictive constraint
    Step 3: Place persons systematically, testing each possibility
    Step 4: When a contradiction arises, backtrack and try another arrangement
    Step 5: Verify final arrangement satisfies ALL constraints
    
    **FAMILY TREE CoT Structure:**
    Step 1: Identify the starting person and their statement
    Step 2: Break down the relationship phrase (e.g., "mother's brother" = maternal uncle)
    Step 3: Build family tree mentally, generation by generation
    Step 4: Trace the path from starting person to the described person
    Step 5: Name the final relationship
    
    **MIXED SERIES CoT Structure:**
    Step 1: Separate the numeric and alphabetic components
    Step 2: Analyze the numeric pattern independently
    Step 3: Analyze the alphabetic pattern independently
    Step 4: Check for grouping patterns (pairs, triplets, etc.)
    Step 5: Apply all identified patterns to predict the next term
    Step 6: Verify the answer matches all observed patterns
    
    **OUTPUT FORMAT - CRITICAL:**
    You MUST output ONLY a valid JSON array. No markdown. No code blocks. No explanations.
    
    Start with [ and end with ]
    
    Example:
    [
      {{
        "question": "Complex multi-step problem requiring systematic analysis?",
        "reasoning": "Step 1: First, let me identify what we know...\\nStep 2: Now I'll test the first possibility. If we assume X, then...\\nStep 3: This leads to a contradiction because...\\nStep 4: So X must be false. Trying the opposite...\\nStep 5: This works! Let me verify by checking all constraints...\\nStep 6: Checking constraint 1: ✓, constraint 2: ✓...",
        "answer": "Final answer with summary: The solution is [answer] because [key insight].",
        "domain": "syllogisms"
      }}
    ]
    
    Output ONLY the JSON array now.
    
    Text:
    {text}
  
  # Quality rating prompt
  qa_rating: |
    Rate each question-answer pair on a scale from 1-10 based on:
    
    **ACCURACY (0-3 points):**
    - Is the logic sound and error-free?
    - Are all reasoning steps valid?
    - Is the final answer correct?
    
    **CLARITY (0-2 points):**
    - Is the question clearly stated?
    - Is the solution easy to follow?
    
    **REASONING QUALITY (0-3 points):**
    - Does it show step-by-step logical deduction?
    - Are assumptions tested properly?
    - Are contradictions identified and resolved?
    
    **EDUCATIONAL VALUE (0-2 points):**
    - Does it teach problem-solving skills?
    - Is the difficulty appropriate?
    
    **DOMAIN-SPECIFIC QUALITY:**
    - Syllogisms: Tests valid inference from multiple premises
    - Seating: Tests systematic constraint satisfaction
    - Family Tree: Tests relationship mapping and tracing
    - Series: Tests pattern recognition across multiple dimensions
    
    YOU MUST RETURN VALID JSON WITH THIS EXACT SCHEMA:
    {{
      "question": "Exact question text",
      "answer": "Exact answer text", 
      "rating": 8
    }}
    
    OR FOR MULTIPLE PAIRS:
    [
      {{"question": "Q1", "answer": "A1", "rating": 8}},
      {{"question": "Q2", "answer": "A2", "rating": 9}}
    ]
    
    *** RETURN ONLY JSON - NO EXPLANATION OR MARKDOWN ***
    
    QA pairs to rate:
    {pairs}